### ISSUE TITLE
Scalingo timeout when deploying

### ISSUE THREAD

**Issue by 6mo** [tristanrobert/keycloak-buildpack#2]
First of all, thank you for this buildpack. It is exactly what i was looking for.

I'm new to buildpacks, i followed the described steps but scalingo timeout : `Timeout: keycloak-instance took more than 60 seconds to boot.`
In the logs, i see this before timeouting: Admin console listening on http://127.0.0.1:9990
I tried to set a specific Port in Env file and Scalingo Env, but keycloak is still exposed in 9990.
Any idea how can i fix this ? 

Also, i don't get how i can play the import/export script. 

Thanks again

**Comment by yahyayouness** [comment]
Did you bind the JBOSS_HTTP_PORT to $PORT in env vars ?
