### ISSUE TITLE
[KEYCLOAK_CLUSTER_MODE] Keycloak in cluster mode in scalingo

### ISSUE THREAD

**Issue by yahyayouness** [tristanrobert/keycloak-buildpack#3]
Hi, thanks for the buildpack 👍 , we deployed Keycloak successfully in Scalingo with standalone mode.

However, we have a question about Keycloak clustering mode with shared infinispan cache.

It's not working because the Scalingo deployment constraint. Did you find a way to run it with cluster mode in scalingo ?

Thanks for your feedback 

[UPDATE] right now, it's not possible to deploy Keycloak with cluster mode in Scalingo. 
The reason is that the containers cannot recognize each others using the discovery protocols of JGroups

**Comment by tristanrobert** [comment]
You find the anwser by yourself!
