### ISSUE TITLE
france-connect moving error 

### ISSUE THREAD

**Issue by MeXaaR** [tristanrobert/keycloak-buildpack#4]
Hi,

I've got an error like that when i use this buildpack to deploy keycloak. 

Do you have an idea about that ?

```shell
mv: cannot move '/build/b035ec16-fdf5-43c6-8e50-9eea683b818f/tmp/keycloak-franceconnect-4.1.0.jar' to '/build/b035ec16-fdf5-43c6-8e50-9eea683b818f/keycloak/standalone/deployments/keycloak-franceconnect.jar': No such file or directory
-----> Add plugin france connect 4.1.0...  !     An error occurred during buildpack compilation
```

**Comment by hrlwfres** [comment]
Hello I think the problem comes from keycloak version 17. I got something similar while deploying keycloak using Docker last week and solved it by using 16.1. I am testing it on this right now (but the scalingo.json edit seems to have no effect)
